services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=pgpassword
      - DATABASE_NAME=db
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app  
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"] 

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
